DELETE http://localhost:3003/api/blogs/64e240d96ad2654f2615e10e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbmFsdGVzdGVyIiwiaWQiOiI2NGU0OWU0YzQxMjQyYjE2MTI0ZmM1Y2EiLCJpYXQiOjE2OTI3MTQ2OTB9.AEPBtYSiiiPK8YvrMF8n4FGA2Rg9z_jfqO9bbV5Vc2Y